### ISSUE TITLE
Gists for Exercises #4 and #5

### ISSUE THREAD

**Issue by saucisson** [cui-unige/modelisation-verification-2017#6]

**Comment by baudgregoire** [comment]
size(list())=0
size(list(l,n))=size(list(l)) + succ(0)

nth(list(n,l),0)=n
nth(list(n,l),m)=nth(list(l), m-succ(0)

**Comment by baudgregoire** [comment]
https://gist.github.com/baudgregoire/9aae3488fa07d5d98fc7fd0443bb1eb1

**Comment by partizanos** [comment]
https://gist.github.com/partizanos/42781cbc05cc8865e3f5ca3c3dd5f4c7

**Comment by pannufle** [comment]
https://gist.github.com/pannufle/4a0287b8b2d987b89fe4c9e5923b5ceb

**Comment by andreasfi** [comment]
https://gist.github.com/andreasfi/440d7a9655c9314f6a1b1c2a27e58578

**Comment by partizanos** [comment]
https://gist.github.com/partizanos/42781cbc05cc8865e3f5ca3c3dd5f4c7

**Comment by saucisson** [comment]
Stacks

**Comment by partizanos** [comment]
https://gist.github.com/partizanos/b7b6254ef387dffd408c6fa1f7e0c7f2

**Comment by pannufle** [comment]
https://gist.github.com/pannufle/8b0648e5b5f8ce60151bb58cd3a0a126

**Comment by sypha** [comment]
https://gist.github.com/sypha/71d9dcd734cf955c259091f38259488a

**Comment by coetaur0** [comment]
https://gist.github.com/coetaur0/7a27dd9c0922aaa17a13a630a528ab16

**Comment by saucisson** [comment]
Maps

**Comment by baudgregoire** [comment]
https://gist.github.com/baudgregoire/86ae34a860a29eb042c1304abb9a5dae

**Comment by saucisson** [comment]
Maps with unique keys

**Comment by pannufle** [comment]
https://gist.github.com/pannufle/a8c054d949f69dbfce54f6ad2ff1e441

**Comment by pannufle** [comment]
https://gist.github.com/pannufle/a8c054d949f69dbfce54f6ad2ff1e441

**Comment by coetaur0** [comment]
https://gist.github.com/coetaur0/8363fdfebebe401f7a7e45f48ccead69
